// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.17.3
// source: servicesMessage.proto

package rpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ServiceAddedNotificationMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MessageType MessageType                           `protobuf:"varint,1,opt,name=messageType,proto3,enum=MessageType" json:"messageType,omitempty"`
	Data        *ServiceAddedNotificationMessage_Data `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *ServiceAddedNotificationMessage) Reset() {
	*x = ServiceAddedNotificationMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_servicesMessage_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ServiceAddedNotificationMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceAddedNotificationMessage) ProtoMessage() {}

func (x *ServiceAddedNotificationMessage) ProtoReflect() protoreflect.Message {
	mi := &file_servicesMessage_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceAddedNotificationMessage.ProtoReflect.Descriptor instead.
func (*ServiceAddedNotificationMessage) Descriptor() ([]byte, []int) {
	return file_servicesMessage_proto_rawDescGZIP(), []int{0}
}

func (x *ServiceAddedNotificationMessage) GetMessageType() MessageType {
	if x != nil {
		return x.MessageType
	}
	return MessageType_PluginRegisterRequest
}

func (x *ServiceAddedNotificationMessage) GetData() *ServiceAddedNotificationMessage_Data {
	if x != nil {
		return x.Data
	}
	return nil
}

type ServiceSetPropertyValueRequestMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MessageType MessageType                                 `protobuf:"varint,1,opt,name=messageType,proto3,enum=MessageType" json:"messageType,omitempty"`
	Data        *ServiceSetPropertyValueRequestMessage_Data `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *ServiceSetPropertyValueRequestMessage) Reset() {
	*x = ServiceSetPropertyValueRequestMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_servicesMessage_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ServiceSetPropertyValueRequestMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceSetPropertyValueRequestMessage) ProtoMessage() {}

func (x *ServiceSetPropertyValueRequestMessage) ProtoReflect() protoreflect.Message {
	mi := &file_servicesMessage_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceSetPropertyValueRequestMessage.ProtoReflect.Descriptor instead.
func (*ServiceSetPropertyValueRequestMessage) Descriptor() ([]byte, []int) {
	return file_servicesMessage_proto_rawDescGZIP(), []int{1}
}

func (x *ServiceSetPropertyValueRequestMessage) GetMessageType() MessageType {
	if x != nil {
		return x.MessageType
	}
	return MessageType_PluginRegisterRequest
}

func (x *ServiceSetPropertyValueRequestMessage) GetData() *ServiceSetPropertyValueRequestMessage_Data {
	if x != nil {
		return x.Data
	}
	return nil
}

type ServicePropertyChangedNotificationMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MessageType MessageType                                     `protobuf:"varint,1,opt,name=messageType,proto3,enum=MessageType" json:"messageType,omitempty"`
	Data        *ServicePropertyChangedNotificationMessage_Data `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *ServicePropertyChangedNotificationMessage) Reset() {
	*x = ServicePropertyChangedNotificationMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_servicesMessage_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ServicePropertyChangedNotificationMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServicePropertyChangedNotificationMessage) ProtoMessage() {}

func (x *ServicePropertyChangedNotificationMessage) ProtoReflect() protoreflect.Message {
	mi := &file_servicesMessage_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServicePropertyChangedNotificationMessage.ProtoReflect.Descriptor instead.
func (*ServicePropertyChangedNotificationMessage) Descriptor() ([]byte, []int) {
	return file_servicesMessage_proto_rawDescGZIP(), []int{2}
}

func (x *ServicePropertyChangedNotificationMessage) GetMessageType() MessageType {
	if x != nil {
		return x.MessageType
	}
	return MessageType_PluginRegisterRequest
}

func (x *ServicePropertyChangedNotificationMessage) GetData() *ServicePropertyChangedNotificationMessage_Data {
	if x != nil {
		return x.Data
	}
	return nil
}

type ServiceGetThingsRequestMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MessageType MessageType                          `protobuf:"varint,1,opt,name=messageType,proto3,enum=MessageType" json:"messageType,omitempty"`
	Data        *ServiceGetThingsRequestMessage_Data `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *ServiceGetThingsRequestMessage) Reset() {
	*x = ServiceGetThingsRequestMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_servicesMessage_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ServiceGetThingsRequestMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceGetThingsRequestMessage) ProtoMessage() {}

func (x *ServiceGetThingsRequestMessage) ProtoReflect() protoreflect.Message {
	mi := &file_servicesMessage_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceGetThingsRequestMessage.ProtoReflect.Descriptor instead.
func (*ServiceGetThingsRequestMessage) Descriptor() ([]byte, []int) {
	return file_servicesMessage_proto_rawDescGZIP(), []int{3}
}

func (x *ServiceGetThingsRequestMessage) GetMessageType() MessageType {
	if x != nil {
		return x.MessageType
	}
	return MessageType_PluginRegisterRequest
}

func (x *ServiceGetThingsRequestMessage) GetData() *ServiceGetThingsRequestMessage_Data {
	if x != nil {
		return x.Data
	}
	return nil
}

type ServiceGetThingsResponseMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MessageType MessageType                           `protobuf:"varint,1,opt,name=messageType,proto3,enum=MessageType" json:"messageType,omitempty"`
	Data        *ServiceGetThingsResponseMessage_Data `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *ServiceGetThingsResponseMessage) Reset() {
	*x = ServiceGetThingsResponseMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_servicesMessage_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ServiceGetThingsResponseMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceGetThingsResponseMessage) ProtoMessage() {}

func (x *ServiceGetThingsResponseMessage) ProtoReflect() protoreflect.Message {
	mi := &file_servicesMessage_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceGetThingsResponseMessage.ProtoReflect.Descriptor instead.
func (*ServiceGetThingsResponseMessage) Descriptor() ([]byte, []int) {
	return file_servicesMessage_proto_rawDescGZIP(), []int{4}
}

func (x *ServiceGetThingsResponseMessage) GetMessageType() MessageType {
	if x != nil {
		return x.MessageType
	}
	return MessageType_PluginRegisterRequest
}

func (x *ServiceGetThingsResponseMessage) GetData() *ServiceGetThingsResponseMessage_Data {
	if x != nil {
		return x.Data
	}
	return nil
}

type ServiceGetThingRequestMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MessageType MessageType                         `protobuf:"varint,1,opt,name=messageType,proto3,enum=MessageType" json:"messageType,omitempty"`
	Data        *ServiceGetThingRequestMessage_Data `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *ServiceGetThingRequestMessage) Reset() {
	*x = ServiceGetThingRequestMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_servicesMessage_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ServiceGetThingRequestMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceGetThingRequestMessage) ProtoMessage() {}

func (x *ServiceGetThingRequestMessage) ProtoReflect() protoreflect.Message {
	mi := &file_servicesMessage_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceGetThingRequestMessage.ProtoReflect.Descriptor instead.
func (*ServiceGetThingRequestMessage) Descriptor() ([]byte, []int) {
	return file_servicesMessage_proto_rawDescGZIP(), []int{5}
}

func (x *ServiceGetThingRequestMessage) GetMessageType() MessageType {
	if x != nil {
		return x.MessageType
	}
	return MessageType_PluginRegisterRequest
}

func (x *ServiceGetThingRequestMessage) GetData() *ServiceGetThingRequestMessage_Data {
	if x != nil {
		return x.Data
	}
	return nil
}

type ServiceGetThingResponseMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MessageType MessageType                          `protobuf:"varint,1,opt,name=messageType,proto3,enum=MessageType" json:"messageType,omitempty"`
	Data        *ServiceGetThingResponseMessage_Data `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *ServiceGetThingResponseMessage) Reset() {
	*x = ServiceGetThingResponseMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_servicesMessage_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ServiceGetThingResponseMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceGetThingResponseMessage) ProtoMessage() {}

func (x *ServiceGetThingResponseMessage) ProtoReflect() protoreflect.Message {
	mi := &file_servicesMessage_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceGetThingResponseMessage.ProtoReflect.Descriptor instead.
func (*ServiceGetThingResponseMessage) Descriptor() ([]byte, []int) {
	return file_servicesMessage_proto_rawDescGZIP(), []int{6}
}

func (x *ServiceGetThingResponseMessage) GetMessageType() MessageType {
	if x != nil {
		return x.MessageType
	}
	return MessageType_PluginRegisterRequest
}

func (x *ServiceGetThingResponseMessage) GetData() *ServiceGetThingResponseMessage_Data {
	if x != nil {
		return x.Data
	}
	return nil
}

type ServiceAddedNotificationMessage_Data struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ServiceId   string `protobuf:"bytes,12,opt,name=serviceId,proto3" json:"serviceId,omitempty"`
	Name        string `protobuf:"bytes,13,opt,name=name,proto3" json:"name,omitempty"`
	PackageName string `protobuf:"bytes,14,opt,name=packageName,proto3" json:"packageName,omitempty"`
}

func (x *ServiceAddedNotificationMessage_Data) Reset() {
	*x = ServiceAddedNotificationMessage_Data{}
	if protoimpl.UnsafeEnabled {
		mi := &file_servicesMessage_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ServiceAddedNotificationMessage_Data) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceAddedNotificationMessage_Data) ProtoMessage() {}

func (x *ServiceAddedNotificationMessage_Data) ProtoReflect() protoreflect.Message {
	mi := &file_servicesMessage_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceAddedNotificationMessage_Data.ProtoReflect.Descriptor instead.
func (*ServiceAddedNotificationMessage_Data) Descriptor() ([]byte, []int) {
	return file_servicesMessage_proto_rawDescGZIP(), []int{0, 0}
}

func (x *ServiceAddedNotificationMessage_Data) GetServiceId() string {
	if x != nil {
		return x.ServiceId
	}
	return ""
}

func (x *ServiceAddedNotificationMessage_Data) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ServiceAddedNotificationMessage_Data) GetPackageName() string {
	if x != nil {
		return x.PackageName
	}
	return ""
}

type ServiceSetPropertyValueRequestMessage_Data struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PluginId     string `protobuf:"bytes,11,opt,name=pluginId,proto3" json:"pluginId,omitempty"`
	ServiceId    string `protobuf:"bytes,12,opt,name=serviceId,proto3" json:"serviceId,omitempty"`
	ThingId      string `protobuf:"bytes,13,opt,name=thingId,proto3" json:"thingId,omitempty"`
	PropertyName string `protobuf:"bytes,14,opt,name=propertyName,proto3" json:"propertyName,omitempty"`
	Value        []byte `protobuf:"bytes,15,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *ServiceSetPropertyValueRequestMessage_Data) Reset() {
	*x = ServiceSetPropertyValueRequestMessage_Data{}
	if protoimpl.UnsafeEnabled {
		mi := &file_servicesMessage_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ServiceSetPropertyValueRequestMessage_Data) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceSetPropertyValueRequestMessage_Data) ProtoMessage() {}

func (x *ServiceSetPropertyValueRequestMessage_Data) ProtoReflect() protoreflect.Message {
	mi := &file_servicesMessage_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceSetPropertyValueRequestMessage_Data.ProtoReflect.Descriptor instead.
func (*ServiceSetPropertyValueRequestMessage_Data) Descriptor() ([]byte, []int) {
	return file_servicesMessage_proto_rawDescGZIP(), []int{1, 0}
}

func (x *ServiceSetPropertyValueRequestMessage_Data) GetPluginId() string {
	if x != nil {
		return x.PluginId
	}
	return ""
}

func (x *ServiceSetPropertyValueRequestMessage_Data) GetServiceId() string {
	if x != nil {
		return x.ServiceId
	}
	return ""
}

func (x *ServiceSetPropertyValueRequestMessage_Data) GetThingId() string {
	if x != nil {
		return x.ThingId
	}
	return ""
}

func (x *ServiceSetPropertyValueRequestMessage_Data) GetPropertyName() string {
	if x != nil {
		return x.PropertyName
	}
	return ""
}

func (x *ServiceSetPropertyValueRequestMessage_Data) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

type ServicePropertyChangedNotificationMessage_Data struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PluginId     string `protobuf:"bytes,11,opt,name=pluginId,proto3" json:"pluginId,omitempty"`
	ServiceId    string `protobuf:"bytes,12,opt,name=serviceId,proto3" json:"serviceId,omitempty"`
	ThingId      string `protobuf:"bytes,13,opt,name=thingId,proto3" json:"thingId,omitempty"`
	PropertyName string `protobuf:"bytes,14,opt,name=propertyName,proto3" json:"propertyName,omitempty"`
	Value        []byte `protobuf:"bytes,15,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *ServicePropertyChangedNotificationMessage_Data) Reset() {
	*x = ServicePropertyChangedNotificationMessage_Data{}
	if protoimpl.UnsafeEnabled {
		mi := &file_servicesMessage_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ServicePropertyChangedNotificationMessage_Data) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServicePropertyChangedNotificationMessage_Data) ProtoMessage() {}

func (x *ServicePropertyChangedNotificationMessage_Data) ProtoReflect() protoreflect.Message {
	mi := &file_servicesMessage_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServicePropertyChangedNotificationMessage_Data.ProtoReflect.Descriptor instead.
func (*ServicePropertyChangedNotificationMessage_Data) Descriptor() ([]byte, []int) {
	return file_servicesMessage_proto_rawDescGZIP(), []int{2, 0}
}

func (x *ServicePropertyChangedNotificationMessage_Data) GetPluginId() string {
	if x != nil {
		return x.PluginId
	}
	return ""
}

func (x *ServicePropertyChangedNotificationMessage_Data) GetServiceId() string {
	if x != nil {
		return x.ServiceId
	}
	return ""
}

func (x *ServicePropertyChangedNotificationMessage_Data) GetThingId() string {
	if x != nil {
		return x.ThingId
	}
	return ""
}

func (x *ServicePropertyChangedNotificationMessage_Data) GetPropertyName() string {
	if x != nil {
		return x.PropertyName
	}
	return ""
}

func (x *ServicePropertyChangedNotificationMessage_Data) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

type ServiceGetThingsRequestMessage_Data struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PluginId     string `protobuf:"bytes,11,opt,name=pluginId,proto3" json:"pluginId,omitempty"`
	ServiceId    string `protobuf:"bytes,12,opt,name=serviceId,proto3" json:"serviceId,omitempty"`
	PropertyName string `protobuf:"bytes,14,opt,name=propertyName,proto3" json:"propertyName,omitempty"`
}

func (x *ServiceGetThingsRequestMessage_Data) Reset() {
	*x = ServiceGetThingsRequestMessage_Data{}
	if protoimpl.UnsafeEnabled {
		mi := &file_servicesMessage_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ServiceGetThingsRequestMessage_Data) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceGetThingsRequestMessage_Data) ProtoMessage() {}

func (x *ServiceGetThingsRequestMessage_Data) ProtoReflect() protoreflect.Message {
	mi := &file_servicesMessage_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceGetThingsRequestMessage_Data.ProtoReflect.Descriptor instead.
func (*ServiceGetThingsRequestMessage_Data) Descriptor() ([]byte, []int) {
	return file_servicesMessage_proto_rawDescGZIP(), []int{3, 0}
}

func (x *ServiceGetThingsRequestMessage_Data) GetPluginId() string {
	if x != nil {
		return x.PluginId
	}
	return ""
}

func (x *ServiceGetThingsRequestMessage_Data) GetServiceId() string {
	if x != nil {
		return x.ServiceId
	}
	return ""
}

func (x *ServiceGetThingsRequestMessage_Data) GetPropertyName() string {
	if x != nil {
		return x.PropertyName
	}
	return ""
}

type ServiceGetThingsResponseMessage_Data struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PluginId  string `protobuf:"bytes,11,opt,name=pluginId,proto3" json:"pluginId,omitempty"`
	ServiceId string `protobuf:"bytes,12,opt,name=serviceId,proto3" json:"serviceId,omitempty"`
	Things    []byte `protobuf:"bytes,14,opt,name=things,proto3" json:"things,omitempty"`
}

func (x *ServiceGetThingsResponseMessage_Data) Reset() {
	*x = ServiceGetThingsResponseMessage_Data{}
	if protoimpl.UnsafeEnabled {
		mi := &file_servicesMessage_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ServiceGetThingsResponseMessage_Data) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceGetThingsResponseMessage_Data) ProtoMessage() {}

func (x *ServiceGetThingsResponseMessage_Data) ProtoReflect() protoreflect.Message {
	mi := &file_servicesMessage_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceGetThingsResponseMessage_Data.ProtoReflect.Descriptor instead.
func (*ServiceGetThingsResponseMessage_Data) Descriptor() ([]byte, []int) {
	return file_servicesMessage_proto_rawDescGZIP(), []int{4, 0}
}

func (x *ServiceGetThingsResponseMessage_Data) GetPluginId() string {
	if x != nil {
		return x.PluginId
	}
	return ""
}

func (x *ServiceGetThingsResponseMessage_Data) GetServiceId() string {
	if x != nil {
		return x.ServiceId
	}
	return ""
}

func (x *ServiceGetThingsResponseMessage_Data) GetThings() []byte {
	if x != nil {
		return x.Things
	}
	return nil
}

type ServiceGetThingRequestMessage_Data struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PluginId  string `protobuf:"bytes,11,opt,name=pluginId,proto3" json:"pluginId,omitempty"`
	ServiceId string `protobuf:"bytes,12,opt,name=serviceId,proto3" json:"serviceId,omitempty"`
	ThingId   string `protobuf:"bytes,13,opt,name=thingId,proto3" json:"thingId,omitempty"`
}

func (x *ServiceGetThingRequestMessage_Data) Reset() {
	*x = ServiceGetThingRequestMessage_Data{}
	if protoimpl.UnsafeEnabled {
		mi := &file_servicesMessage_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ServiceGetThingRequestMessage_Data) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceGetThingRequestMessage_Data) ProtoMessage() {}

func (x *ServiceGetThingRequestMessage_Data) ProtoReflect() protoreflect.Message {
	mi := &file_servicesMessage_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceGetThingRequestMessage_Data.ProtoReflect.Descriptor instead.
func (*ServiceGetThingRequestMessage_Data) Descriptor() ([]byte, []int) {
	return file_servicesMessage_proto_rawDescGZIP(), []int{5, 0}
}

func (x *ServiceGetThingRequestMessage_Data) GetPluginId() string {
	if x != nil {
		return x.PluginId
	}
	return ""
}

func (x *ServiceGetThingRequestMessage_Data) GetServiceId() string {
	if x != nil {
		return x.ServiceId
	}
	return ""
}

func (x *ServiceGetThingRequestMessage_Data) GetThingId() string {
	if x != nil {
		return x.ThingId
	}
	return ""
}

type ServiceGetThingResponseMessage_Data struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PluginId  string `protobuf:"bytes,11,opt,name=pluginId,proto3" json:"pluginId,omitempty"`
	ServiceId string `protobuf:"bytes,12,opt,name=serviceId,proto3" json:"serviceId,omitempty"`
	Thing     []byte `protobuf:"bytes,14,opt,name=thing,proto3" json:"thing,omitempty"`
}

func (x *ServiceGetThingResponseMessage_Data) Reset() {
	*x = ServiceGetThingResponseMessage_Data{}
	if protoimpl.UnsafeEnabled {
		mi := &file_servicesMessage_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ServiceGetThingResponseMessage_Data) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceGetThingResponseMessage_Data) ProtoMessage() {}

func (x *ServiceGetThingResponseMessage_Data) ProtoReflect() protoreflect.Message {
	mi := &file_servicesMessage_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceGetThingResponseMessage_Data.ProtoReflect.Descriptor instead.
func (*ServiceGetThingResponseMessage_Data) Descriptor() ([]byte, []int) {
	return file_servicesMessage_proto_rawDescGZIP(), []int{6, 0}
}

func (x *ServiceGetThingResponseMessage_Data) GetPluginId() string {
	if x != nil {
		return x.PluginId
	}
	return ""
}

func (x *ServiceGetThingResponseMessage_Data) GetServiceId() string {
	if x != nil {
		return x.ServiceId
	}
	return ""
}

func (x *ServiceGetThingResponseMessage_Data) GetThing() []byte {
	if x != nil {
		return x.Thing
	}
	return nil
}

var File_servicesMessage_proto protoreflect.FileDescriptor

var file_servicesMessage_proto_rawDesc = []byte{
	0x0a, 0x15, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x11, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x54, 0x79, 0x70, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xe8, 0x01, 0x0a, 0x1f, 0x53,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x41, 0x64, 0x64, 0x65, 0x64, 0x4e, 0x6f, 0x74, 0x69, 0x66,
	0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x2e,
	0x0a, 0x0b, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x54, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0e, 0x32, 0x0c, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x54, 0x79, 0x70,
	0x65, 0x52, 0x0b, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12, 0x39,
	0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x25, 0x2e, 0x53,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x41, 0x64, 0x64, 0x65, 0x64, 0x4e, 0x6f, 0x74, 0x69, 0x66,
	0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x44,
	0x61, 0x74, 0x61, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x1a, 0x5a, 0x0a, 0x04, 0x44, 0x61, 0x74,
	0x61, 0x12, 0x1c, 0x0a, 0x09, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x49, 0x64, 0x18, 0x0c,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x49, 0x64, 0x12,
	0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x0d, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x70, 0x61, 0x63, 0x6b, 0x61, 0x67, 0x65, 0x4e, 0x61,
	0x6d, 0x65, 0x18, 0x0e, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x70, 0x61, 0x63, 0x6b, 0x61, 0x67,
	0x65, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0xaf, 0x02, 0x0a, 0x25, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x53, 0x65, 0x74, 0x50, 0x72, 0x6f, 0x70, 0x65, 0x72, 0x74, 0x79, 0x56, 0x61, 0x6c, 0x75,
	0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12,
	0x2e, 0x0a, 0x0b, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x54, 0x79, 0x70, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0e, 0x32, 0x0c, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x54, 0x79,
	0x70, 0x65, 0x52, 0x0b, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12,
	0x3f, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x2b, 0x2e,
	0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x53, 0x65, 0x74, 0x50, 0x72, 0x6f, 0x70, 0x65, 0x72,
	0x74, 0x79, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x4d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61,
	0x1a, 0x94, 0x01, 0x0a, 0x04, 0x44, 0x61, 0x74, 0x61, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x6c, 0x75,
	0x67, 0x69, 0x6e, 0x49, 0x64, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x6c, 0x75,
	0x67, 0x69, 0x6e, 0x49, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x49, 0x64, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x74, 0x68, 0x69, 0x6e, 0x67, 0x49, 0x64, 0x18, 0x0d,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x74, 0x68, 0x69, 0x6e, 0x67, 0x49, 0x64, 0x12, 0x22, 0x0a,
	0x0c, 0x70, 0x72, 0x6f, 0x70, 0x65, 0x72, 0x74, 0x79, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x0e, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0c, 0x70, 0x72, 0x6f, 0x70, 0x65, 0x72, 0x74, 0x79, 0x4e, 0x61, 0x6d,
	0x65, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x0f, 0x20, 0x01, 0x28, 0x0c,
	0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0xb7, 0x02, 0x0a, 0x29, 0x53, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x50, 0x72, 0x6f, 0x70, 0x65, 0x72, 0x74, 0x79, 0x43, 0x68, 0x61, 0x6e, 0x67,
	0x65, 0x64, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x2e, 0x0a, 0x0b, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x54, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0c, 0x2e, 0x6d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x54, 0x79, 0x70, 0x65, 0x52, 0x0b, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x54, 0x79, 0x70, 0x65, 0x12, 0x43, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x2f, 0x2e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x50, 0x72, 0x6f,
	0x70, 0x65, 0x72, 0x74, 0x79, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x64, 0x4e, 0x6f, 0x74, 0x69,
	0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e,
	0x44, 0x61, 0x74, 0x61, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x1a, 0x94, 0x01, 0x0a, 0x04, 0x44,
	0x61, 0x74, 0x61, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x49, 0x64, 0x18,
	0x0b, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x49, 0x64, 0x12,
	0x1c, 0x0a, 0x09, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x49, 0x64, 0x18, 0x0c, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x09, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x49, 0x64, 0x12, 0x18, 0x0a,
	0x07, 0x74, 0x68, 0x69, 0x6e, 0x67, 0x49, 0x64, 0x18, 0x0d, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x74, 0x68, 0x69, 0x6e, 0x67, 0x49, 0x64, 0x12, 0x22, 0x0a, 0x0c, 0x70, 0x72, 0x6f, 0x70, 0x65,
	0x72, 0x74, 0x79, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x0e, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x70,
	0x72, 0x6f, 0x70, 0x65, 0x72, 0x74, 0x79, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x76,
	0x61, 0x6c, 0x75, 0x65, 0x18, 0x0f, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x22, 0xf0, 0x01, 0x0a, 0x1e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x47, 0x65, 0x74,
	0x54, 0x68, 0x69, 0x6e, 0x67, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x4d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x12, 0x2e, 0x0a, 0x0b, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x54,
	0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0c, 0x2e, 0x6d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x54, 0x79, 0x70, 0x65, 0x52, 0x0b, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x54, 0x79, 0x70, 0x65, 0x12, 0x38, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x24, 0x2e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x47, 0x65, 0x74, 0x54,
	0x68, 0x69, 0x6e, 0x67, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x4d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x1a, 0x64,
	0x0a, 0x04, 0x44, 0x61, 0x74, 0x61, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e,
	0x49, 0x64, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e,
	0x49, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x49, 0x64, 0x18,
	0x0c, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x49, 0x64,
	0x12, 0x22, 0x0a, 0x0c, 0x70, 0x72, 0x6f, 0x70, 0x65, 0x72, 0x74, 0x79, 0x4e, 0x61, 0x6d, 0x65,
	0x18, 0x0e, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x70, 0x72, 0x6f, 0x70, 0x65, 0x72, 0x74, 0x79,
	0x4e, 0x61, 0x6d, 0x65, 0x22, 0xe6, 0x01, 0x0a, 0x1f, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x47, 0x65, 0x74, 0x54, 0x68, 0x69, 0x6e, 0x67, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x2e, 0x0a, 0x0b, 0x6d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x54, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0c, 0x2e,
	0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x54, 0x79, 0x70, 0x65, 0x52, 0x0b, 0x6d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12, 0x39, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x25, 0x2e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x47, 0x65, 0x74, 0x54, 0x68, 0x69, 0x6e, 0x67, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x52, 0x04, 0x64,
	0x61, 0x74, 0x61, 0x1a, 0x58, 0x0a, 0x04, 0x44, 0x61, 0x74, 0x61, 0x12, 0x1a, 0x0a, 0x08, 0x70,
	0x6c, 0x75, 0x67, 0x69, 0x6e, 0x49, 0x64, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70,
	0x6c, 0x75, 0x67, 0x69, 0x6e, 0x49, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x73, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x49, 0x64, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x73, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x74, 0x68, 0x69, 0x6e, 0x67, 0x73, 0x18,
	0x0e, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x06, 0x74, 0x68, 0x69, 0x6e, 0x67, 0x73, 0x22, 0xe4, 0x01,
	0x0a, 0x1d, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x47, 0x65, 0x74, 0x54, 0x68, 0x69, 0x6e,
	0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12,
	0x2e, 0x0a, 0x0b, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x54, 0x79, 0x70, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0e, 0x32, 0x0c, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x54, 0x79,
	0x70, 0x65, 0x52, 0x0b, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12,
	0x37, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x23, 0x2e,
	0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x47, 0x65, 0x74, 0x54, 0x68, 0x69, 0x6e, 0x67, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x44, 0x61,
	0x74, 0x61, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x1a, 0x5a, 0x0a, 0x04, 0x44, 0x61, 0x74, 0x61,
	0x12, 0x1a, 0x0a, 0x08, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x49, 0x64, 0x18, 0x0b, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x08, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x49, 0x64, 0x12, 0x1c, 0x0a, 0x09,
	0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x49, 0x64, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x09, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x74, 0x68,
	0x69, 0x6e, 0x67, 0x49, 0x64, 0x18, 0x0d, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x74, 0x68, 0x69,
	0x6e, 0x67, 0x49, 0x64, 0x22, 0xe2, 0x01, 0x0a, 0x1e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x47, 0x65, 0x74, 0x54, 0x68, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x2e, 0x0a, 0x0b, 0x6d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x54, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0c, 0x2e, 0x6d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x54, 0x79, 0x70, 0x65, 0x52, 0x0b, 0x6d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12, 0x38, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x24, 0x2e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x47,
	0x65, 0x74, 0x54, 0x68, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x4d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x52, 0x04, 0x64, 0x61, 0x74,
	0x61, 0x1a, 0x56, 0x0a, 0x04, 0x44, 0x61, 0x74, 0x61, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x6c, 0x75,
	0x67, 0x69, 0x6e, 0x49, 0x64, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x6c, 0x75,
	0x67, 0x69, 0x6e, 0x49, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x49, 0x64, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x68, 0x69, 0x6e, 0x67, 0x18, 0x0e, 0x20, 0x01,
	0x28, 0x0c, 0x52, 0x05, 0x74, 0x68, 0x69, 0x6e, 0x67, 0x42, 0x18, 0x5a, 0x16, 0x2e, 0x2e, 0x2f,
	0x2e, 0x2e, 0x2f, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x2d, 0x67, 0x72, 0x70, 0x63, 0x3b,
	0x72, 0x70, 0x63, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_servicesMessage_proto_rawDescOnce sync.Once
	file_servicesMessage_proto_rawDescData = file_servicesMessage_proto_rawDesc
)

func file_servicesMessage_proto_rawDescGZIP() []byte {
	file_servicesMessage_proto_rawDescOnce.Do(func() {
		file_servicesMessage_proto_rawDescData = protoimpl.X.CompressGZIP(file_servicesMessage_proto_rawDescData)
	})
	return file_servicesMessage_proto_rawDescData
}

var file_servicesMessage_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_servicesMessage_proto_goTypes = []interface{}{
	(*ServiceAddedNotificationMessage)(nil),                // 0: ServiceAddedNotificationMessage
	(*ServiceSetPropertyValueRequestMessage)(nil),          // 1: ServiceSetPropertyValueRequestMessage
	(*ServicePropertyChangedNotificationMessage)(nil),      // 2: ServicePropertyChangedNotificationMessage
	(*ServiceGetThingsRequestMessage)(nil),                 // 3: ServiceGetThingsRequestMessage
	(*ServiceGetThingsResponseMessage)(nil),                // 4: ServiceGetThingsResponseMessage
	(*ServiceGetThingRequestMessage)(nil),                  // 5: ServiceGetThingRequestMessage
	(*ServiceGetThingResponseMessage)(nil),                 // 6: ServiceGetThingResponseMessage
	(*ServiceAddedNotificationMessage_Data)(nil),           // 7: ServiceAddedNotificationMessage.Data
	(*ServiceSetPropertyValueRequestMessage_Data)(nil),     // 8: ServiceSetPropertyValueRequestMessage.Data
	(*ServicePropertyChangedNotificationMessage_Data)(nil), // 9: ServicePropertyChangedNotificationMessage.Data
	(*ServiceGetThingsRequestMessage_Data)(nil),            // 10: ServiceGetThingsRequestMessage.Data
	(*ServiceGetThingsResponseMessage_Data)(nil),           // 11: ServiceGetThingsResponseMessage.Data
	(*ServiceGetThingRequestMessage_Data)(nil),             // 12: ServiceGetThingRequestMessage.Data
	(*ServiceGetThingResponseMessage_Data)(nil),            // 13: ServiceGetThingResponseMessage.Data
	(MessageType)(0), // 14: messageType
}
var file_servicesMessage_proto_depIdxs = []int32{
	14, // 0: ServiceAddedNotificationMessage.messageType:type_name -> messageType
	7,  // 1: ServiceAddedNotificationMessage.data:type_name -> ServiceAddedNotificationMessage.Data
	14, // 2: ServiceSetPropertyValueRequestMessage.messageType:type_name -> messageType
	8,  // 3: ServiceSetPropertyValueRequestMessage.data:type_name -> ServiceSetPropertyValueRequestMessage.Data
	14, // 4: ServicePropertyChangedNotificationMessage.messageType:type_name -> messageType
	9,  // 5: ServicePropertyChangedNotificationMessage.data:type_name -> ServicePropertyChangedNotificationMessage.Data
	14, // 6: ServiceGetThingsRequestMessage.messageType:type_name -> messageType
	10, // 7: ServiceGetThingsRequestMessage.data:type_name -> ServiceGetThingsRequestMessage.Data
	14, // 8: ServiceGetThingsResponseMessage.messageType:type_name -> messageType
	11, // 9: ServiceGetThingsResponseMessage.data:type_name -> ServiceGetThingsResponseMessage.Data
	14, // 10: ServiceGetThingRequestMessage.messageType:type_name -> messageType
	12, // 11: ServiceGetThingRequestMessage.data:type_name -> ServiceGetThingRequestMessage.Data
	14, // 12: ServiceGetThingResponseMessage.messageType:type_name -> messageType
	13, // 13: ServiceGetThingResponseMessage.data:type_name -> ServiceGetThingResponseMessage.Data
	14, // [14:14] is the sub-list for method output_type
	14, // [14:14] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_servicesMessage_proto_init() }
func file_servicesMessage_proto_init() {
	if File_servicesMessage_proto != nil {
		return
	}
	file_messageType_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_servicesMessage_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ServiceAddedNotificationMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_servicesMessage_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ServiceSetPropertyValueRequestMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_servicesMessage_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ServicePropertyChangedNotificationMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_servicesMessage_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ServiceGetThingsRequestMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_servicesMessage_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ServiceGetThingsResponseMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_servicesMessage_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ServiceGetThingRequestMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_servicesMessage_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ServiceGetThingResponseMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_servicesMessage_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ServiceAddedNotificationMessage_Data); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_servicesMessage_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ServiceSetPropertyValueRequestMessage_Data); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_servicesMessage_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ServicePropertyChangedNotificationMessage_Data); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_servicesMessage_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ServiceGetThingsRequestMessage_Data); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_servicesMessage_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ServiceGetThingsResponseMessage_Data); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_servicesMessage_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ServiceGetThingRequestMessage_Data); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_servicesMessage_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ServiceGetThingResponseMessage_Data); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_servicesMessage_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_servicesMessage_proto_goTypes,
		DependencyIndexes: file_servicesMessage_proto_depIdxs,
		MessageInfos:      file_servicesMessage_proto_msgTypes,
	}.Build()
	File_servicesMessage_proto = out.File
	file_servicesMessage_proto_rawDesc = nil
	file_servicesMessage_proto_goTypes = nil
	file_servicesMessage_proto_depIdxs = nil
}
